before:
  hooks:
    - go mod tidy
builds:
  - id: "default"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./cmd/community
    binary: community
archives:
  - builds:
      - default
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    name_template: "community_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: beyondstorage
    name: go-community
